name: Lint and test

on: [push, pull_request]

jobs:
  ci:
    name: run ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: gosec
        run: make gosec
